team-aliens/DMS-Backend

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/JwtFilter.kt

토큰이 있을 경우 영속성 컨텍스트에 인증 객체를 넣은 후에 
영속성 컨텍스트를 초기화하기 때문에 모든 요청을 익명의 사용자로 판단하게 됩니다.
따라서 영속성 컨텍스트를 초기화한 후 인증 객체를 넣었습니다.
- 없음
- resolved #133

merge: (#133) 토큰 인증 오류 해결

---

dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/ReissueResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/TokenResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/SignUpResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityProperties.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/GenerateJwtAdapter.kt

- GenerateJwtAdapter
- ReissueResponse 
- SignInResponse
- 모든 Token Response 사용하는 Usecase  & Test
- resolved #139

merge: (#139) Refresh Token 만료시간 추가

---

dms-application/src/main/kotlin/team/aliens/dms/common/extension/LocalDateExtension.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/meal/spi/QueryMealPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/MealPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/repository/MealJpaRepository.kt

- 해당 날짜의 급식이 존재하지 않는 경우 아침, 점심, 저녁에 각각 "급식이 없습니다." 문구 출력
- QueryMealsResponse에 팩터리 메서드 패턴 적용
- resolved #141

merge: (#141) 급식 조회 API 변경

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailCodeWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/GetStudentListWebRequest.kt

- ``?`` 처리에 따른 request 변환 과정에 ``!`` 추가
- resolved #

merge: 커스텀 타입의 @NotNull 필드 nullable 필드로 변경

---

dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/AuthCodeLimitNotFoundException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt

- CertifyEmailCodeUseCase 로직 변경 (새로운 uuid 생성 방지, 이미 인증된 경우 예외 처리)
- AuthCodeLimit.certified() 메서드 변경 (새로운 uuid 생성 방지)
- resolved #167

merge: (#167) AuthCodeLimit 매번 새로운 UUID 저장됨

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudentQueryStudyRoomsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/StudyRoomVO.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/vo/QueryStudyRoomVO.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

- Security Configuration GET /study-rooms/list/students
- StudyRoomPersistenceAdapter queryAllStudyRoomsBySchoolId 메소드 추가
- resolved #204

merge: (#204) 자습실 목록 보기 학생 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/Seat.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt

- seat.use(), seat.unUse() 메서드로 변경
- studyRoom.apply(), studyRoom.unApply() 메서드로 변경
- resolved #210

merge: (#210) 자습실 신청, 취소 비즈니스 로직 수정

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/ParseFilePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/usecase/ImportVerifiedStudentUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/CommandStudentPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Sex.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/VerifiedStudent.kt
dms-infrastructure/build.gradle.kts
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/exception/ExcelExtensionMismatchException.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/exception/ExcelInvalidFileException.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/exception/ExcelSexMismatchException.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/file/FileExtension.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/file/FileWebAdapter.kt

- ExcelAdapter
- VerifiedStudentPersistenceAdapter
- resolved #176

merge: (#176) 검증된 학생 엑셀 파일 DB 저장 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryPointPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryPointHistoryResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointQueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryPointPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointHistoryJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/mapper/PointHistoryMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/vo/QueryPointHistoryVO.kt

- entity 컬럼을 수정헀습니다.
- 상벌점 total을 불러오는 로직을, 최근 History을 조회하여 가져오는 방식으로 변경했습니다.
- resolved #222

merge: (#222) PointHistory 비정규화

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/PluginVersions.kt
dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQueryUserPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/CreateRemainOptionUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/CreateRemainUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/request/CreateRemainOptionWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/response/CreateRemainOptionResponse.kt

- CreateRemainOptionUseCase
- resolved #229

merge: (#229) 잔류 항목 생성 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainOptionNotFoundException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainOptionUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainOptionUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainOptionErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/request/UpdateRemainOptionWebRequest.kt

- 잔류 항목 수정 api
- resolved #243

merge: (#243) 잔류 항목 수정 api

---

build.gradle.kts
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
dms-application/src/main/kotlin/team/aliens/dms/common/dto/PageData.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryAllPointHistoryResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryAllPointHistoryUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryAllPointHistoryUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/vo/QueryAllPointHistoryVO.kt
dms-presentation/src/main/kotlin/team/aliens/dms/common/dto/PageWebData.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt

- 전체 상벌점 내역 보기 api
- PageData는 앞으로 공용으로 사용될 수 있을 것 같아서 application 모듈의 common 패키지에 정의해놓았습니다
- mockk 의존성은 이전 PR이 아직 머지되지 않아서 일단 같이 커밋했습니다
- 앞으로 테스트를 작성할때도 mockk를 계속 사용할지는 이야기가 더 필요할 것 같아요!
- resolved #240

merge: (#240) 전체 상벌점 내역 보기 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/point/exception/PointHistoryNotFoundException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/CommandPointHistoryPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointHistoryPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CancelGrantedPointUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CancelGrantedPointUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointHistoryErrorCode.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/point/exception/PointHistoryCanNotCancelException.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
dms-domain/src/test/kotlin/team/aliens/dms/point/model/PointHistoryTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt

- 상벌점 부여 취소 api
- domain 모듈에 있는 PointHistory model에 취소 내역을 반환하는 메서드를 만들었습니다.
- resolved #249

merge: (#249) 상벌점 부여 취소 api 

---

dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/PointHistoryDto.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryPointHistoryResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryStudentPointHistoryResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/PointHistoryVO.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointHistoryUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryStudentPointHistoryUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryStudentPointHistoryUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt

- 학생 상벌점 내역 조회 기능 추가
- 기존의 상벌점 내역조회(`QueryPointHistoryUseCase`)에 페이징 추가
- resolved #256

merge: (#256) 학생 상벌점 내역 조회api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/UpdateRemainAvailableTimeRequest.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainAvailableTimePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainAvailableTimePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainAvailableTimePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainAvailableTimeUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/UpdateRemainAvailableTimeUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainAvailableTimePersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/dto/request/UpdateRemainAvailableTimeWebRequest.kt

- 잔류 신청 시간 설정 API
- resolved #234

merge: (#234) 잔류 신청 시간 설정 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/RemoveRemainOptionUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/RemoveRemainOptionUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainStatusJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt

- 잔류 항목 삭제 api
- 이전 PR이랑 동일한 클래스 추가된건, 머지할때 conflict 해결하면서 합치겠습니다
- resolved #264

merge: (#264) 잔류 항목 삭제 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/RemainStatusInfo.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/StudentRemainInfo.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/response/ExportRemainStatusResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQuerySchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Sex.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/vo/RemainStatusInfoVO.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt

- 학생 잔류 신청내역 엑셀 출력 api
- 성별 한국어 companion object로 있던거 이동했습니다
- remain 도메인에서 student 엔티티를 건들면 도메인끼리 주는 영향이 커질 것 같아서, 쿼리를 따로 날리도록 분리했습니다. (학생 쿼리 1번 +  remainStatus에 대한 쿼리 1번)
신청하지 않은 학생은 빈칸입니다
- resolved #261

merge: (#261) 학생 잔류 신청내역 엑셀 출력 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/QueryRemainOptionsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainAvailableTimePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainQueryRemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainOptionPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainOptionJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt

- 잔류 신청 항목 목록 보기 API
- resolved #262

merge: (#262) 잔류 신청 항목 목록 보기 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/remain/exception/RemainCanNotAppliedException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/CommandRemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/ApplyRemainUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/error/RemainAvailableTimeErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainStatusJpaEntity.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt

merge: (#269) 잔류 신청 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/entity/StudentJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/mapper/StudentMapper.kt

- student table에 deletedAt 추가
- 조회시 user에 있는 deleteAt으로 join 해서 걸러도 되긴 합니다
- 근데 user 정보가 필요 없을때도 매번 조인해야하고, jpql이 조금 복잡해진다는 단점이 있어서 비정규화 시켜놨습니다
- (그리고 그렇게 하려면 @Where annotation을 사용할 수 없어서, 매번 쿼리에 조인과 비교문을 추가해줘야 할 수도 있습니다)
- 의견 있으시다면 말씀해주세요
- resolved #300

merge: (#300) 삭제된 student 조회 막기

---

dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CancelGrantedPointUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CancelGrantedPointUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
dms-domain/src/test/kotlin/team/aliens/dms/point/model/PointHistoryTests.kt

- 해당 부여 내역이 아닌, 최근 내역으로 total 계산하도록 변경

bug: cancel시 최근 total 기준으로 계산

---

dms-application/src/main/kotlin/team/aliens/dms/domain/auth/exception/UnverifiedAuthCodeException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/AuthCodeLimitPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryAuthCodeLimitPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/error/AuthErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt

- 회원가입에서 인증코드 검사 제거
- resolved #329

merge: (#329) 인증코드 검사 삭제

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/GrantPointWebRequest.kt

- web request 값은 스프링에서 주입해주는거라서 List의 요소가 자바 객체이면서 null인 경우엔 null check를 못하는 것 같습니다..
- 그래서 수동으로 체크해서 에러 던지는 코드를 추가했습니다
- 반환되는 에러 형식이 그냥 validation 하는거랑 다르긴 해서 다른 방법에 대한 아이디어 있으시면 말씀해주세용 
- resolved #

merge: List 요소 validation 안됨

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/TimeSlotInUseException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveTimeSlotUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveTimeSlotUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomWebRequest.kt

- api 개발
- timeSlotId size 제한 설정
- resolved #358

merge: (#358) 이용시간 삭제 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/ManagerQueryStudyRoomResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/QueryTimeSlotsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/StudentQueryStudyRoomResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryTimeSlotsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

- api 개발
- 자습실 상세 조회시 이용시간 목록 반환
- LocalTime 반환 format 고정
- resolved #360

merge: (#360) 이용시간 조회 api + 자습실 상세 조회시 이용시간 정보 반환

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/GetStudentDetailsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryTagPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt

merge: (#386) 학생 상세 확인 API 수정

---

dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCaseTests.kt

- 태그 색상만 변경하려고 하면 TagAlreadyExistsException이 반환되서 제거했습니다
- resolved #397

merge: (#397) 태그 수정 시 중복 예외 제거

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt

- QueryStudentsUseCase
- StudentPersistenceAdapter
- resolved #390

merge: (#390) tag 필터링 추가

---

.github/workflows/dev-cd.yml
.github/workflows/prod-cd.yml

elgohr/Publish-Docker-Github-Action@master is not supported anymore

Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QuerySeatTypePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QuerySeatTypesUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/stub/StudyRoomStub.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/QuerySeatTypesUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/SeatTypePersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

studyRoomId 있는 경우
studyRoomId 없는 경우
- resolved #414

merge: (#414) 자습실에 해당하는 seatType 조회

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt

 merge: (#419) 학생 자습실 조회 학년, 성별 조건문 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt

merge: (#450) 탈퇴시 유저만 삭제

---

dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/BaseUUIDEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notice/entity/NoticeJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/entity/PhraseJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointFilterJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointHistoryJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointOptionJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/mapper/PhraseMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainOptionJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/room/entity/RoomJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/school/entity/SchoolJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/entity/StudentJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatTypeJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/TimeSlotJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/entity/TagJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/user/entity/UserJpaEntity.kt

- persistable 상속 받지 않고 UUID가 UUID(0,0)인 경우 null로 들어가도록 해주었음
- persistable을 재정의 하는 방법을 고려해보았으나 알 수 없는 에러 발생
- resolved #483

merge: (#483) entity 첫 저장시 merge로 인한 select query 방지

---

dms-core/src/main/kotlin/team/aliens/dms/domain/point/dto/PointResponse.kt

- class를 합치는건 리팩토링 목적에 크게 벗어나는 것 같아서 두 이름으로 모두 반환하도록 설정해놓았습니다
- 나중에 꼭 지워야합니다.
- 구버전 지원하기 위해 필드명, url 바뀌는건 항상 이런식으로 해놨다가 나중에 수정해야할 것 같아용..
- 
- 
- resolved #

chore: pointHistory response 필드명

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/exception/NotificationErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/exception/NotificationExceptions.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandDeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandNotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandTopicSubscriptionPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/DeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/NotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryNotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryTopicSubscriptionPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/TopicSubscriptionPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/RemoveAllNotificationUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/RemoveMyAllNotificationUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/RemoveNotificationUseCase.kt
dms-infrastructure/config/detekt/detekt.yml
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/NotificationOfPersistenceAdapterOfUser.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/NotificationOfUserJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt

merge: (#527) 알림 삭제 api 

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingApplication.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/outing/model/OutingApplicationTest.kt

chore: (#605) 외출 취소 확인 로직 변경

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/port/ExcelPort.kt

- ExcelAdapter에서 분리할 메서드를 ExcelPort 로 분리
- ExcelPort를 ExcelAdapter에 상속하도록 변경
- resolved #671

merge: (#671) 엑셀 API 메서드 분리

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/response/OutingResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/CurrentOutingApplicationVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetCurrentOutingApplicationUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryCurrentOutingApplicationVO.kt

- 신청자, 동행자 쿼리를 하나로 병합
- 쿼리 로직 수정 (자신이 포함된 외출 그룹에서 결과물에 자신 제외)
- queryCurrentOutingApplicationAsCompanionVO 쿼리 삭제
- resolved #679

merge: (#679) 동행자가 내 외출 신청 조회 쿼리 버그 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt

merge: publishNotificationToApplicant 사용으로 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt

- queryDeviceTokensByUserIds 쿼리 추가
- resolved #705

merge: (#705) 외출 신청 동행자 알람 미발행 버그 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentGetAllStudentsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandStudentTagPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryStudentTagPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/StudentTagPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt

- 사용하지 않는 메서드들 까지 정리함
- 
- resolved #716

merge: (#716) 학생 조회 api 에 schoolId 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryTopicSubscriptionPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/ToggleSubscriptionUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/TopicSubscriptionPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/TopicSubscriptionJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt

merge: (#719) 알림 구독/해제 API 병합

---

buildSrc/src/main/kotlin/Dependencies.kt
dms-infrastructure/build.gradle.kts
dms-persistence/src/main/kotlin/team/aliens/dms/global/config/CacheConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/global/config/CacheName.kt
dms-persistence/src/main/kotlin/team/aliens/dms/global/config/CustomKeyGenerator.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerApplicationJpaRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt

- CacheConfig
-- 캐시 설정을 모아뒀습니다
- CustomKeyGenerator 
-- key를 메서드 명으로 생성해줌으로써 구분해줄 수 있도록 하였습니다
- 원래 CacheConfig에 상수를 넣어주려했는데 persistence에도 필요하고 presentation 계층에도 필요해서 하드코딩 했습니다
- redis관련 dependencis가 persistence에 있어서 persistence에 cacheConfig 등을 뒀습니다
- 캐싱 처리가 필요해보이는 도메인을 말해주시면 추가해서 올리겠습니다
- resolved #737

feat: (#737) 캐싱 적용

---

dms-infrastructure/src/main/resources/application.yml

merge: (#745) 토큰 시간 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTime.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTimeTest.kt

merge: (#747) 외출 제약 조건 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentResponse.kt

merge: (#750) 캐시 적용 에러 해결

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentResponse.kt

- Kotlin Jackson 도입 실패..
- 
- resolved #757

refactor: (#757) Jackson 생성자 지정

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/VolunteerWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/CreateVolunteerWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/UpdateVolunteerWebRequest.kt

merge: (#772) RequestBody Int 필드 nullcheck 안되는 오류 해결

---

dms-core/src/main/kotlin/team/aliens/dms/domain/school/dto/SchoolResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/model/AvailableFeature.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/school/stub/SchoolStub.kt
dms-infrastructure/src/main/resources/db/migration/V7__add_column_in_tbl_available_feature.sql
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/school/entity/AvailableFeatureJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/school/mapper/AvailableFeatureMapper.kt

- 풀리퀘 번호 777이라 신나네요!
- 
- resolved #777

merge: (#777) volunteer service 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/VolunteerApplicationStatus.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/service/GetVolunteerServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/QueryVolunteerApplicationPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/QueryVolunteerPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/CurrentVolunteerApplicantVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/VolunteerWithCurrentApplicantVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/ManagerGetAllVolunteersUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/QueryAvailableVolunteersUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/UnapplyVolunteerUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryCurrentVolunteerApplicantVO.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryVolunteerWithCurrentApplicantVO.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/VolunteerWebAdapter.kt

- VO 추가
- Response of 메서드의 매개 변수 클래스를 VO 로 변경
- status ENUM 추가 (노션에 명세 해놨습니다)
- response 에 status가 추가됨에 따라 approved 필드를 제거
- 쿼리의 반환값을 List<Pair<>> 에서 List<Triple<>> 로 변경
- 현재 봉사자에 따른 신청제약은 서버에서 처리하지 않습니다.
- resolved #774

merge: (#774) 봉사 활동 목록 조회 Response 에 CurrentApplicants 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/CurrentVolunteerApplicantVO.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryCurrentVolunteerApplicantVO.kt

merge: (#783) id 필드 추가 및 name 필드 명 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/CreateVolunteerRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/UpdateVolunteerRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/response/VolunteerResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/Volunteer.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/spi/vo/VolunteerWithCurrentApplicantVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/CreateVolunteerUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/usecase/UpdateVolunteerUseCase.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/school/stub/SchoolStub.kt
dms-infrastructure/src/main/resources/db/migration/V8__delete_column_in_tbl_volunteer.sql
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/VolunteerPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/vo/QueryVolunteerWithCurrentApplicantVO.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/VolunteerWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/CreateVolunteerWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/volunteer/dto/request/UpdateVolunteerWebRequest.kt

merge: (#785) volunteer content 삭제

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/response/OutingResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingApplication.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingStatus.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/CurrentOutingApplicationVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingApplicationVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingHistoryVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ApplyOutingUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ExportAllOutingApplicationsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetOutingApplicationHistoriesUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UnApplyOutingUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UpdateOutingStatusUseCase.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/outing/model/OutingApplicationTest.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/outing/stub/OutingStub.kt
dms-infrastructure/src/main/resources/db/migration/V9__change_column_in_table_outinga_application.sql
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingApplicationMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryCurrentOutingApplicationVO.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingApplicationVO.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingHistoryVO.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt

- outingStatus 삭제 및 isApproved와 isComeback을 추가했습니다
- 
- resolved #788

merge: (#788) 외출 내역 조회 API 변경

---

README.md
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetCurrentOutingApplicationUseCase.kt

사용하지 않는 조건문 삭제했습니다
- 
- 
- resolved #795

merge: (#795) 쓸모없는 조건문 제거

---

.github/workflows/xquare-cd-prod.yml

2025년 2월 1일부터 actions/cache 의 v1-v2를 종료합니다 (이 [변경 로그 발표](https://app.github.media/e/er?s=88570519&lid=6815&elqTrackId=08a5e2ee0de44b669cfee44c72a218f2&elq=a03ae9e6b46c431a96ca345bbad99b2c&elqaid=4282&elqat=1&elqak=8AF5E7AAA12E3C7C230E5849DC6FF5707A506F974B68867C08DD3502A54AFC88073A) 에서 자세히 읽어보세요)  actions/toolkit 의 @actions/cache 패키지 의 모든 이전 버전도 종료 합니다. 발표된 사용 중단 날짜 이후에 @actions/cache 패키지 또는 actions/cache 버전을 사용하려고 하면 워크플로 오류가 발생합니다. 캐시 작업의 특정 버전이나 SHA에 고정된 경우 2월 1일 이후에도 워크플로가 실패합니다.
필요한 작업:
지원되는 버전의 actions/cache를 사용하도록 워크플로를 업데이트하고 @actions/cache 패키지를 기반으로 하는 작업이나 다른 제품을 4.0.0 이상으로 업그레이드하는 것이 좋습니다.
| **actions/cache 버전 올리면서 구 버전인 다른 요소들도 버전업 해줬습니다**
- resolved #814

merge: (#814) 워크플로우 버전 업그레이드

---

dms-presentation/src/main/kotlin/team/aliens/dms/common/extension/FileExtension.kt

Windows에서 파일 이름에 사용할 수 없는 문자 변경
'||' → '_' 로 변경하였습니다
- resolved #816

merge: (#816) Windows에서 파일 이름에 사용할 수 없는 문자 변경

---

dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt

select(pointHistoryJpaEntity.createdAt.max()) 서브 쿼리 <-  join으로 대체
substring를 gcn에 사용하여 인덱스가 무시당하는 이슈 <- eq로 대체 
‭ ‭ ‭
- 지금 조인 형태가 student - pointhistory 의 LeftJoin 형식인데 
join 형식으로 변경하여 벌점을 받은 학생만 조회 하도록 변경하였습니다
‭ ‭ ‭
- padStart 사용해서 학생 번호 처리해주었습니다
https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.text/pad-start.html
‭ ‭ ‭
‭ ‭ ‭
- resolved #840

merge: (#840) 상벌점 토탈 조회 쿼리 리팩토링

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CommandNoticeServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryVotePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryVotesUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/UpdateVotingTopicUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotePersistenceAdapter.kt

* 투표결과 조회 쿼리 모범학생, 학생투표로 분리함
* 기존에 "임시" 로 되어있던 투표 결과 공지로 보내는 기능을 실제 투표 결과로 보내게 수정
* QueryVotesUseCase 에서 보내는 투표결과를 모범학생, 학생으로 분리해서 결과 가져오게 함.
* votePersistenceAdapter 에서 JPA 표현식을 사용하여 최대한 queryDSL 코드를 분리함
* QueryVoteUseCase
* VotePersistenceAdapter
* CommandNoticeServiceImpl
- resolved #844

merge: (#844) 투표 결과 조회 쿼리 모범학생, 학생 분리 및 관련된 기능 전체 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VoteResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryVotesUseCase.kt

- 기존 투표 주제 이름 확인 불가능하던 api에서 확인 가능하게 변경
- resolved #881

merge: (#881) 투표 결과 조회 시 투표 주제 이름도 같이 보여주게 변경
