dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetails.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetailsService.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetails.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt

- Security filter chain
- BCrypt Password
- resolved #1

merge: (#1) Security 세팅

---

dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCode.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/EmailType.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/RefreshToken.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeLimitMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/RefreshTokenMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeLimitEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/RefreshTokenEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeEntityRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/RefreshTokenRepository.kt

merge: (#6) NoSQL Entity

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
dms-application/build.gradle.kts
dms-application/src/main/kotlin/team/aliens/dms/global/annotation/ReadOnlyUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/global/annotation/UseCase.kt
dms-domain/src/main/kotlin/team/aliens/dms/global/annotation/DomainService.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/aop/GlobalComponentScan.kt

merge: (#13) annotation setting

---

.github/workflows/CI.yml
.github/workflows/build.yml
build.gradle.kts
codecov.yml

- .github/workflows build.yml
- root build.gradle jacoco report
- resolved #12

merge: (#12) code coverage

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/ErrorResponse.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorHandler.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/exception/InternalServerErrorException.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetails.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetailsService.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetails.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/JwtParser.kt

- JwtParser$getAuthentication() token type 검사
- javadoc 삭제
- resolved #21

merge: (#21) security principle

---

buildSrc/src/main/kotlin/PluginVersions.kt
dms-application/build.gradle.kts
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/SecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/exception/AnswerNotMatchedException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQuerySchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryUserPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindAccountIdUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
dms-application/src/main/kotlin/team/aliens/dms/global/spi/CoveredEmailPort.kt
dms-application/src/main/kotlin/team/aliens/dms/global/util/CoveredEmailPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/FindAccountIdUseCaseTest.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/error/ManagerErrorCode.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/manager/exception/ManagerNotFoundException.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityFacadeAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/util/StingUtil.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/utils/StingUtils.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/SchoolPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/manager/WebManagerAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/user/dto/response/FindAccountIdResponse.kt

merge: (#19) FindAccountId Api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/QuerySchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolQuestionUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolQuestionUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QuerySchoolsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolController.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/response/SchoolQuestionResponse.kt

- GET /schools/question/{school-id} permission
- test package school.usecase -> domain.school.usecase
- resolved #25

merge: (#24) query question api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/exception/AnswerNotMatchedException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindAccountIdUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/exception/AnswerNotMatchedException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolAnswerUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/FindAccountIdUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolAnswerUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/school/error/SchoolErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt

- GET /schools/answer/{school-id}
- manager domain의 web adapter
- FindAccountIdUseCase 로직 수정
- AnswerNotMatchedException 위치
- resolved #26

merge: (#26) school answer api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/school/exception/CodeNotMatchedException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCaseTest.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/school/error/SchoolErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/response/SchoolIdResponse.kt

- security configuration GET /code/{school-id}
- resolved #38

merge: (#38) 학교 인증코드 검사 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryAuthCodeLimitPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryAuthCodePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryAuthCodePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCaseTest.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCode.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodePersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeLimitMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/mapper/AuthCodeMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/model/AuthCodeLimitEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeEntityRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/auth/repository/AuthCodeLimitRepository.kt

- AuthCodeEntity & AuthCode 요소 변경 (userId -> email)
- AuthCodeLimitEntity & AuthCodeLimit 요소 변경 (userId -> email)
- resolved #53

merge: (#53) send email code api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/QuerySchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/CheckSchoolCodeUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/SchoolPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/repository/SchoolJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt

- querySchoolByCode 메서드 추가
- resolved #51

merge: (#51) check school code api 수정

---

dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CheckAccountIdExistenceUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/CheckAccountIdExistenceUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/auth/AuthWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/auth/dto/response/CheckAccountIdExistenceResponse.kt

- security configuration GET /auth/account-id
- resolved #48

merge: (#48) 아이디 존재 여부 확인 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/NoticePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/QueryNoticePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeStatusUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeStatusUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/model/Notice.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/NoticePersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/entity/NoticeJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/mapper/NoticeMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/repository/NoticeJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/notice/dto/response/GetNoticeStatusResponse.kt

- /notices/status permission
- resolved #58

merge: (#58) get notice status api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt

- SignupUseCase -> SignUpUseCase
- resolved #57

merge: (#57) signup test

---

buildSrc/src/main/kotlin/Dependencies.kt
dms-infrastructure/build.gradle.kts
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/AwsProperties.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/ConfigurationPropertiesConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSesConfig.kt
dms-infrastructure/src/main/resources/application.yml

merge: (#67) aws autoconfigure dependency 추가

---

dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/exception/IsNotWriterException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/exception/NoticeNotFoundException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/CommandNoticePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/NoticePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/NoticeSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/spi/QueryNoticePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/RemoveNoticeUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/exception/SchoolMismatchException.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/RemoveNoticeUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/notice/error/NoticeErrorCode.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/school/error/SchoolErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/notice/NoticePersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/notice/NoticeWebAdapter.kt

- DELETE /notices/{notice-id} permission
- resolved #79

merge: (#79) remove notice api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/model/Meal.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/entity/MealJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/mapper/MealMapper.kt

- Meal Domail Model & Entity
- QueryMealsUseCase
- QueryMealsResponse
- resolved #89

merge: (#89) 급식 엔티티 칼로리 정보 컬럼 추가

---

dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/model/Meal.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/entity/MealJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/meal/mapper/MealMapper.kt

This reverts commit 7a86ba3b8b88fa7c4dc8f0098505993df5b7c935.
- cal info 제거
- resolved #89

Revert "merge: (#89) 급식 엔티티 칼로리 정보 컬럼 추가"

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/JwtFilter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/CustomAccessDeniedHandler.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/CustomAuthenticationEntryPoint.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/error/SecurityErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/ForbiddenException.kt

- entryPoint & deniedHandler 등록
- ExceptionFilter 버그 수정
- JwtFilter 잘못된 처리 수정
- resolved #

merge: security & exception filtering

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/manager/ManagerWebAdapter.kt

- security configuration DELETE /managers/students/student-id
- resolved #75

merge: (#75) 학생 삭제 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/student/dto/request/UpdateStudentProfileWebRequest.kt

- security configuration PATCH /students/profile
- resolved #96

merge: (#96) 프로필 수정 API

---

dms-application/src/main/kotlin/team/aliens/dms/common/util/StringUtil.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentListUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointHistoryPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentMyPageResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryPointHistoryPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentDetailsUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/GetStudentListUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/student/StudentWebAdapter.kt

- security configuration GET /students/profile
- string util의 gcn 함수 student domain에 field로 변경
- resolved #95

merge: (#95) 마이페이지 확인 API

---

dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/dto/UpdateQuestionRequest.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/CommandSchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolQueryUserPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/UpdateQuestionUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/UpdateQuestionUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/SchoolPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/SchoolWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/school/dto/request/UpdateQuestionWebRequest.kt

- security configuration 정렬
- resolved #101

merge: (#101) 확인질문 설정 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/user/usecase/UserPasswordCompareUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/user/usecase/UserPasswordCompareUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/user/UserWebAdapter.kt

- security configuration GET /users/password
- update user password api 휴먼에러 해결
- resolved #105

merge: (#105) 비밀번호 비교 API 

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSESAdapter.kt

- try/catch -> runCatching
- printStackTrace
- resolved #114

merge: (#114) AWS SES 수정

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/NeisSchoolInfoJpaEntity.kt

merge: (#119) Neis 학교 정보 엔티티 세팅

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/SchoolJpaEntity.kt

- school jpa entity
- resolved hotfix

merge: 이름 & 주소 Unique 컬럼 설정

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/SchoolWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt

- Notice Web Adapter
- School Web Adapter
- Student Web Adapter
- resolved #124

merge: (#124) QueryString Snake Case로 변경

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/JwtParser.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/entity/UserJpaEntity.kt

- UserJpaEntity
- JwtParser
- resolved #

merge: Authority Number 에러

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/AuthWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailCodeWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/CertifyEmailWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/CheckStudentGcnWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/FindStudentAccountIdWebRequest.kt

- AuthWebAdapter
- StudentWebAdapter
- auth & student web request
- resolved #128

merge: (#128) Modelattribute Validation 에러

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryUserPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/FindManagerAccountIdUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt

merge: (#13) find manager account id usecase

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/GetStudentListWebRequest.kt

merge: (#134) 학생 검색 API 버그

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/SchoolJpaEntity.kt

- SchoolJpaEntity
- resolved #

merge: 학교 이름 컬럼 변경

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt

merge: 공지 목록 확인 API 버그

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/meal/MealWebAdapter.kt

merge: 급식 날짜 Format

---

dms-presentation/src/main/kotlin/team/aliens/dms/common/WebMvcConfig.kt

- WebMvcConfig
- resolved #143

merge: (#143) PATCH 메소드 CORS 발생 

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/ErrorResponse.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorHandler.kt

- ErrorResponse
- GlobalErrorHandler
- resolved #145

merge: (#145) 유효성 검사 에러 핸들링 추가

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/Password.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/ResetPasswordManagerWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/ResetStudentPasswordWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/SignUpWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/UserWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/dto/request/UpdateUserPasswordWebRequest.kt

- password class -> object
- resolved #154

merge: (#154) 비밀번호 관련 요청 버그

---

dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Sex.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoom.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/StudyRoomAvailableTime.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomAvailableTimeJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/StudyRoomJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/StudyRoomAvailableTimeMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/StudyRoomMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomAvailableTimeJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomJpaRepository.kt

자습실
- StudyRoomJpaEntity
- StudyRoomJpaRepository
- StudyRoomMapper
- StudyRoom
자습실 신청 시간
- StudyRoomAvailableTimeJpaEntity
- StudyRoomAvailableTimeJpaRepository
- StudyRoomAvailableTimeMapper
- StudyRoomAvailableTime
- 자습실
- 자습실 신청 시간
- resolved #169

merge: (#169) 자습실 & 자습실 신청 시간 엔티티 세팅

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/RedisConfig.kt
dms-infrastructure/src/main/resources/application.yml

- application.yml에 spring.redis.password 추가
- resolved #171

merge: (#171) redis readonly replica 오류 해결

---

dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/Seat.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/SeatStatus.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/model/SeatType.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatTypeJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/mapper/SeatTypeMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatTypeJpaRepository.kt

자리
- SeatJpaEntity
- SeatJpaRepository
- SeatMapper
- Seat
자리 종류
- SeatTypeJpaEntity
- SeatTypeJpaRepository
- SeatTypeMapper
- SeatType
- 자리
- 자리 종류
- resolved #172

merge: (#172) 자리 & 종류 엔티티 세팅

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/UpdateAvailableTimeUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandAvailableTimePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomAvailableTimePort.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomAvailableTimePersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateAvailableTimeWebRequest.kt

- 자습실 신청 시간 설정 API permission
- resolved #179

merge: (#179) 자습실 신청 시간 설정 API

---

.github/workflows/stage-cd.yml
Dockerfile

merge: (#188) stage 배포 시 healthcheck 기능 추가

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatTypeAlreadyExistsException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandSeatTypePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QuerySeatTypePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/SeatTypePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateSeatTypeUseCase.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatTypeErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/SeatTypePersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatTypeJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateSeatTypeWebRequest.kt

- Security Configuration POST /study-rooms/types
- SeatTypePersistenceAdapter
- resolved #185

merge: (#185) 자리 종류 생성 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomRequest.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomAlreadyExistsException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/entity/SeatJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomResponse.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/WebSeatStatus.kt

- 자습실 생성 API permissioin
- resolved #182

merge: (#182) 자습실 생성 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomRequest.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/StudyRoomJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomWebRequest.kt

- 자습실 수정 API permission
- existsStudyRoomByFloorAndName 메서드 학교별로 조회하도록 변경
- resolved #186

merge: (#186) 자습실 수정 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveStudyRoomUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

- 자습실 삭제 API permission
- resolved #187

merge: (#187) 자습실 삭제 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/ManagerQueryStudyRoomsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomsUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

- Security Configuration GET /study-rooms/list/managers
- resolved #207

merge: (#207) 자습실 목록 보기 관리자 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatTypeInUseException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/SeatTypeNotFoundException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandSeatTypePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QuerySeatTypePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/SeatTypeQueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveSeatTypeUseCase.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/SeatTypeErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/SeatTypePersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

- Security Configuration DELETE /study-rooms/types/{type-id}
- resolved #209

merge: (#209) 자리 종류 삭제 API

---

dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomAvailableGradeMismatchException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/StudyRoomAvailableSexMismatchException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomQueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt

-  ApplySeatUseCase
- resolved #

merge: 자습실 자리 신청 API 학년 & 성별 검사 추가

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomRequest.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/AuthWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SendEmailCodeWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/WebEmailType.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/dto/request/ResetPasswordManagerWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/NoticeWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/CreateNoticeWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/UpdateNoticeWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notice/dto/request/WebOrderType.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/dto/request/UpdateQuestionWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/ResetStudentPasswordWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/SignUpWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/dto/request/UpdateStudentProfileWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateSeatTypeWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateStudyRoomWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/WebSex.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/user/dto/request/UpdateUserPasswordWebRequest.kt

- 모든 Web Adapter & Request
- resolved #215

merge: (#215) 모든 Web 요청 Validation 추가

---

dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/CheckStudentGcnUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/CheckStudentGcnUseCaseTests.kt

- CheckStudentGcnUseCase
- resolved #218

merge: (#218) 학번검사 학생 -> 인증된 학생

---

dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainOption.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainRecord.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainOptionJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainRecordJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/mapper/RemainOptionMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/mapper/RemainRecordMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainOptionJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainRecordJpaRepository.kt

merge: (#225) 잔류 항목 & 신청 기록 엔티티 세팅

---

dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/QueryPointOptionsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/QueryPointOptionsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointOptionsUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointOptionJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt

- 상벌점 항목조회 기능추가
- 키워드 조회
- resolved #254

merge: (#254) 상벌점 항목 조회

---

dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainStatus.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/entity/RemainStatusJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/mapper/RemainStatusMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainStatusJpaRepository.kt

ddl update로 해놓으면 테이블명 수정이 아니라 그냥 새 테이블이 생겨서, sql 쿼리 날린다음 머지하겠습니다
```sql
RENAME TABLE tbl_remain_record TO tbl_remain_status;
```
- resolved #259

merge: (#259) remainRecord -> remainStatus 

---

dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/CreatePointOptionRequest.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/CreatePointOptionResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/exception/PointOptionNameExistsException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/CommandPointOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/PointOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointOptionPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CreatePointOptionUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/RemovePointOptionUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CreatePointOptionUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/RemovePointOptionUseCaseTest.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/point/error/PointOptionErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointOptionJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/CreatePointOptionWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/WebPointType.kt

- 상벌점 항목 삭제 생성 api 개발
- resolved #237

merge: (#237) 상벌점 항목 생성&삭제

---

dms-application/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainAvailableTimeUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainAvailableTimeUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/remain/model/RemainAvailableTime.kt

merge: (#248) 조회시 검사 삭제

---

dms-application/src/main/kotlin/team/aliens/dms/domain/point/dto/UpdatePointOptionRequest.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/CreatePointOptionUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/UpdatePointOptionUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/UpdatePointOptionUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/dto/request/UpdatePointOptionWebRequest.kt

- 상벌점 항목 변경 api개발
- path value 유효성 검사 추가
- resolved #273

merge: (#273) 상벌점 항목 변경

---

dms-application/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/school/model/AvailableFeature.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/entity/AvailableFeatureJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/school/mapper/AvailableFeatureMapper.kt

- 기존 데이터 있어서 컬럼 수정해놓고 머지해야할 것 같습니다
- resolved #276

merge: (#276) remainService 추가

---

dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/CommandStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt

merge: (#280) 회원가입시 verifiedStudent 삭제

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandRemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerCommandStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/spi/RemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentCommandRemainStatusPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentCommandStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/AppliedSeatNotFoundException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/StudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryCurrentAppliedStudyRoomUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentWithdrawalUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/QueryCurrentAppliedStudyRoomUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/remain/repository/RemainStatusJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt

- 학생 탈퇴 api
- removeUserUseCase 500 가능성 있는거 수정
- Exception명 이상한거 보여서 수정
- resolved #278

merge: (#278) 학생 탈퇴 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/GetStudentDetailsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/QueryStudentsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentMyPageResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCase.kt

merge: (#283) 학생 정보 조회 성별 추가

---

dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/GetStudentDetailsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/dto/QueryStudentsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/manager/spi/ManagerQueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/remain/dto/StudentRemainInfo.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/StudentQueryRoomPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentDetailsUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/QueryStudentsUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/manager/usecase/RemoveStudentUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryPointHistoryUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/QueryStudentPointHistoryUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/CheckStudentGcnUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/FindStudentAccountIdUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/StudentMyPageUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentProfileUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/room/model/Room.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/Student.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/VerifiedStudent.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/room/RoomPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/room/entity/RoomJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/room/repository/RoomJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/entity/VerifiedStudentJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt

- RoomJpaEntity name String으로
- VerifiedStudentJpaEntity roomNumber String으로
- 그외 도메인모델 및 request, response객체의 roomNumber String으로
- resolved #287

merge: (#287) 호실번호 타입 변경

---

dms-application/src/main/kotlin/team/aliens/dms/domain/file/usecase/UploadFileUseCase.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/auth/model/EmailType.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/email/AwsSESAdapter.kt
dms-infrastructure/src/main/resources/templates/find_account_id_template.html
dms-infrastructure/src/main/resources/templates/password_template.html
dms-infrastructure/src/main/resources/templates/signup_template.html

feat: email template 수정

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/BaseTimeEntity.kt
dms-infrastructure/src/main/resources/application.yml

- application.yml
- resolved #295

merge: (#295) JPA Dialect 변경

---

dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/exception/BadExcelFormatException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/FileQuerySchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/FileQueryUserPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/FileSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/spi/ParseFilePort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/file/usecase/ImportVerifiedStudentUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/SchoolPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/file/error/FileErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt

- numericCellValue 말고 stringCellValue으로 바꾼 이유는 호실 번호를 String으로 바꿔야 하기 때문입니다
- resolved #285

merge: (#285) 엑셀 학생 등록 api 수정

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ResetAllStudyRoomsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatJpaRepository.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/StudyRoomScheduler.kt

- study room port
- study room scheduler
- resolved #302

merge: (#302) 자습실 자리 초기화

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt

- url 접근 권한 순서 변경
- resolved #305

merge: (#305) 잔류 신청 시간 설정 접근 권한 오류

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt

merge: pointFilter 오류 수정

---

buildSrc/src/main/kotlin/Dependencies.kt
dms-application/build.gradle.kts
dms-application/src/main/kotlin/team/aliens/dms/domain/school/aop/AvailableFeatureAspect.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/exception/FeatureNotAvailableException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/spi/QuerySchoolPort.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/school/error/SchoolErrorCode.kt

- aop로 availableFeature 조회 및 검증
- resolved #298

merge: (#298) 이용 불가능한 기능 접근시 에러 

---

dms-application/src/main/kotlin/team/aliens/dms/domain/meal/dto/QueryMealsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/meal/usecase/QueryMealsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/GrantPointUseCase.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/meal/model/Meal.kt

merge: 급식 조회 오류 해결

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/entity/UserJpaEntity.kt

- 삭제된 학생 조회 방지
삭제된 유저로 로그인시 404

feat: 삭제된 학생 조회 방지

---

dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/repository/StudentJpaRepository.kt

feat: 학번 존재 체크

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt

- PointHistoryPersistenceAdapter
- resolved #324

bug: (#324) 상벌점 내역 출력 시 취소 내역 제외

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/UserPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/user/repository/UserJpaRepository.kt

- UserPersistenceAdapter
- resolved #323

merge: (#323) 삭제된 학생 포함 조회

---

dms-application/src/main/kotlin/team/aliens/dms/domain/school/dto/QueryAvailableFeaturesResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/school/SchoolWebAdapter.kt

merge: (#327) 사용가능 기능 조회api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/file/usecase/ImportVerifiedStudentUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/point.usecase/CancelGrantedPointUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/student/model/VerifiedStudent.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt

- StudentPersistenceAdapter
- ImportVerifiedStudentUseCase
- resolved #317

merge: (#317) 학생 중복 검사

---

.github/workflows/dev-cd.yml
.github/workflows/prod-cd.yml

- dev-cd.yml 추가
- resolved #303

merge: (#303) Prod Dev 환경분리

---

.github/workflows/CI.yml
.github/workflows/build.yml

- CI.yml
- build.yml
- resolved #340

merge: (#340) CI Trigger수정

---

buildSrc/src/main/kotlin/Dependencies.kt
dms-infrastructure/build.gradle.kts
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt

merge: localDateTime response format config

---

dms-domain/src/main/kotlin/team/aliens/dms/domain/point/model/PointFilter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/entity/PointFilterJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/mapper/PointFilterMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointFilterJpaRepository.kt

- PointFilterEntity
- PointFilterRepository
- PointFilterMapper
- resolved #339

merge: (#339) 상벌점 필터 엔티티 세팅

---

.github/workflows/dev-cd.yml

merge: (#347) DevCD Trigger변경

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt
dms-infrastructure/src/main/resources/application.yml

- jackson2ObjectMapperBuilder bean 등록한거 때문에 yml에서 property-naming-strategy 설정한게 안먹혀서 설정 추가해줬습니다
- resolved #

bug: snake case

---

.github/workflows/prod-cd.yml

- prod가 v로 시작하는 태그에대한 push에 trigger되게 변경
- v0.0.1
- resolved #353

merge: (#353) trigger to tag

---

dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/TimeSlotAlreadyExistException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/TimeSlotAlreadyExistsException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCaseTests.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/studyroom/error/StudyRoomErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/TimeSlotJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateTimeSlotWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/CreateTimeSlotWebResponse.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateTimeSlotWebRequest.kt

merge: (#355) 이용시간 생성, 수정 api

---

dms-application/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/dto/QueryTagsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/dto/TagResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagQueryUserPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagSecurityPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/QueryTagsUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/user/spi/UserPort.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/stub/TagStub.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/QueryTagsUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/repository/TagJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt

- TagPersistenceAdapter
- QueryTagsUseCase
- resolved #366

merge: (#366) 태그 리스트 조회

---

dms-application/src/main/kotlin/team/aliens/dms/domain/file/usecase/UploadFileUseCase.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/exception/TagAlreadyExistsException.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandTagPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/TagPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/CreateTagUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ManagerQueryStudyRoomUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/stub/TagStub.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/CreateTagUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/QueryTagsUseCaseTest.kt
dms-domain/src/main/kotlin/team/aliens/dms/domain/tag/error/TagErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/mapper/TagMapper.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/repository/TagJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/dto/CreateTagWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/dto/CreateTagWebResponse.kt

- CreateTagUseCase
- resolved #372

merge: (#372) 태그 추가 api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandTagPort.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCaseTest.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/common/util/FileUtil.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt

- 태그 삭제 USECASE
- resolved #376

merge: (#376) remove tag

---

dms-application/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/CreateTagUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/QueryTagsUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCaseTests.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCaseTest.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/TagWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/tag/dto/UpdateTagWebRequest.kt

merge: (#394) updateTag api

---

dms-application/src/main/kotlin/team/aliens/dms/domain/point/usecase/ExportAllPointHistoryUseCase.kt

merge: 상벌점 내역 엑셀 출력 list empty 버그

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfiguration.kt

- JacksonConfiguration
- resolved #399

merge: (#399) LocalDate format오류

---

dms-application/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt

- SecurityConfiguation
- resolved #407

merge: (#407) 사용가능 기능 조회 학생 권한 추가

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt

- excel 등록할때, 빈 row인데 lastRow 값이 잘못 인식되어 업로드가 안되는 경우 있음
- row의 첫 셀이 비어있으면 그 row를 읽지 않도록 설정
- resolved #

chore: excel 값 없는 row 예외처리

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt

- 기존에는 태그 여러개 선택시, 그 태그 중 하나를 가진 학생이 모두 조회되었음 -> or
- 태그 여러개 선택시, 그 태그를 모두 가진 학생이 조회되도록 수정 -> and
- studentTags로 tagIds를 모두 가지고 있는 studentId를 반환하는 서브쿼리(갯수가 동일한지 확인)를 where문에 추가하였습니다.
- resolved #411

merge: (#411) 학생 tag filter 조건문 변경

---

dms-application/src/main/kotlin/team/aliens/dms/domain/notice/dto/QueryNoticeDetailsResponse.kt
dms-application/src/main/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeDetailsUseCase.kt
dms-application/src/test/kotlin/team/aliens/dms/domain/notice/usecase/QueryNoticeDetailsUseCaseTests.kt

merge: (#416) 공지 상세 id 조회

---

.github/workflows/dev-cd.yml
.github/workflows/prod-cd.yml
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/persistence/room/entity/RoomJpaEntity.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

setting: network 연결 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/manager/spi/QueryManagerPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/point/model/PointHistoryTests.kt
dms-infrastructure/build.gradle.kts
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetailsService.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/manager/ManagerPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt

- ManagerDetailsService
- StudentDetailssService
- resolved #427

merge: (#427) lazy로딩 문제

---

dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/QueryStudyRoomPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatApplicationJpaRepository.kt

merger: QueryStudyRoom isMine 로직 변경

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
dms-infrastructure/build.gradle.kts
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/filter/ExceptionFilter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt
dms-infrastructure/src/main/resources/application.yml

- ExeptionFilter
- resolved #425

merge: (#425) logging추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/CommandStudyRoomPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/StudyRoomPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/studyroom/repository/SeatApplicationJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/studyroom/StudyRoomWebAdapter.kt

- UnApplySeatUseCase
- resolved #438

merge: (#438) 자습실 취소 시 모든 신청이 다 취소되는 오류

---

dms-core/src/main/kotlin/team/aliens/dms/common/error/ErrorProperty.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/exception/error/AuthErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/exception/error/FileErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/manager/exception/error/ManagerErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notice/exception/error/NoticeErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/exception/error/PointHistoryErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/exception/error/PointOptionErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/exception/error/RemainAvailableTimeErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/exception/error/RemainOptionErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/exception/error/RemainStatusErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/room/exception/error/RoomErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/exception/error/SchoolErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/exception/error/StudentErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/exception/error/VerifiedStudentErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/AvailableTimeErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/SeatErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/SeatTypeErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/exception/error/StudyRoomErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/exception/error/TagErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/user/exception/error/UserErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/ErrorResponse.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/exception/error/SecurityErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/error/OtherServerErrorCode.kt
dms-infrastructure/src/main/resources/application.yml

merge: (#433) 에러코드 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/spi/vo/StudentSeatInfo.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/StudentQueryStudyRoomsUseCase.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomStudentsApplicationStatusUseCaseTests.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt

chore: (#436) studyroom excel 신청 여러개인 경우 출력 오류

---

dms-core/src/main/kotlin/team/aliens/dms/common/error/DynamicDmsException.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/exception/BadExcelFormatException.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/error/GlobalErrorCode.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/exception/BadExcelFormatException.kt

- 엑셀 에러메시지 동적으로 생성되도록 함
- 프론트쪽에는 따로 전달해서 작업 예정
- resolved #457

merge: (#457) 엑셀 동적 에러메시지 구현

---

dms-core/src/main/kotlin/team/aliens/dms/domain/auth/model/AuthCodeLimit.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/AuthService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/CheckAuthCodeService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/CommandAuthCodeService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/GetAuthCodeService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/CheckAuthCodeServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/CommandAuthCodeServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/GetAuthCodeServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/ReissueTokenUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SendEmailCodeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ResetManagerPasswordUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/service/GetSchoolServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/ResetStudentPasswordUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt

merge: (#449) auth facade

---

dms-core/src/main/kotlin/team/aliens/dms/domain/file/usecase/ImportStudentUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/room/service/CommandRoomService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/room/service/CommandRoomServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/room/service/RoomService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/room/spi/CommandRoomPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/room/spi/QueryRoomPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/room/spi/RoomPort.kt

merge: (#466) room Facade 분리

---

dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CheckTagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CheckTagServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/TagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandTagPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/CancelGrantedTagUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/CreateTagUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/GrantTagUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/QueryTagsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/RemoveTagUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateTagUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/StudentTagPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt

- tag facade분리
- resolved #463

merge: (#463) tag facade분리

---

dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/manager/dto/ExportStudentResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/ExportStudentUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/ExportRemainStatusUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfiguration.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt

merge: (#473) 학생 정보 출력 api

---

dms-core/src/main/kotlin/team/aliens/dms/domain/manager/usecase/UpdateStudentGcnByFileUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/SignUpUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ExportStudyRoomApplicationStatusUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UnApplySeatUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/ComponentScanConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/JacksonConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/config/PropertiesScanConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/config/EnableSchedulingConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/config/EnableFeignClientsConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt

merge: config로 명칭 통일

---

dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/GetRemainService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/GetRemainServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/spi/QueryRemainStatusPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/remain/RemainStatusPersistenceAdapter.kt

- userId -> studentId
- resolved #509

merge: (#509) 내 잔류 신청항목 보기 버그

---

dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/service/CommandStudyRoomService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/service/CommandStudyRoomServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateSeatTypeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateStudyRoomUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/CreateTimeSlotUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateAvailableTimeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCase.kt

merge: (#505) StudyRoomService create, update method 분리

---

dms-core/src/main/kotlin/team/aliens/dms/common/spi/SecurityPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/dto/PointResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/dto/RemainResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/GetRemainService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/service/GetRemainServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryCurrentAppliedRemainOptionUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/remain/usecase/QueryRemainOptionsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/dto/UpdateStudyRoomRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/service/CommandStudyRoomService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/service/CommandStudyRoomServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/ApplySeatUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/RemoveTimeSlotUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateStudyRoomUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/studyroom/usecase/UpdateTimeSlotUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityAdapter.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/CustomDetails.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetails.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/ManagerDetailsService.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetails.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/principle/StudentDetailsService.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/remain/RemainWebAdapter.kt

- 잔류 옵션 UUID 반환
- resolved #512

merge: (#512) 내 잔류 신청항목 보기 api 수정

---

dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt

- StudentPersistenceAdapter
- resolved #519

merge :: (#519) n+1

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/dto/NotificationResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/NotificationOfUser.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/entity/NotificationOfUserJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/mapper/NotificationOfUserMapper.kt

merge: (#529) linkIdenfier로 변경, isRead 삭제

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/dto/NotificationResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandDeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandNotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/DeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryNotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryTopicSubscriptionPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/TopicSubscriptionPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/ExportStudentUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/ImportStudentUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/QueryStudentDetailsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/QueryStudentsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/RemoveStudentUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentGcnByFileUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/UpdateStudentRoomByFileUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/file/FileWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/manager/ManagerWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt

refactor: (#531) manager api student domain으로 이동

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryNotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/QueryMyNotificationsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/notification/FCMConfig.kt
dms-infrastructure/src/main/resources/application.yml
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/NotificationOfPersistenceAdapterOfUser.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/NotificationOfUserJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt

feat: notification 조회 paging

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/exception/OutingNotFoundException.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/exception/error/OutingErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingApplication.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingStatus.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingType.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingTypeJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingApplicationMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingTypeMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/OutingApplicationJpaRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/OutingTypeJpaRepository.kt

merge: (#538) 외출 신청 & 외출 타입 엔티티 세팅

---

dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingApplicationVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingCompanionVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ExportAllOutingApplicationsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingApplicationVO.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingCompanionVO.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt

merge: (#556) 외출 신청내역 엑셀 출력 api

---

buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/DependencyVersions.kt
dms-infrastructure/src/main/resources/application.yml
dms-persistence/build.gradle.kts

merge: (#561) flyway 적용

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/ApplyOutingRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingApplication.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ApplyOutingUseCase.kt
dms-infrastructure/src/main/resources/db/migration/V1__drop_reason_destination_in_tbl_outing_application.sql
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/entity/OutingApplicationJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/mapper/OutingApplicationMapper.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/ApplyOutingWebRequest.kt

merge: (#563) 외출 신청 사유, 장소 삭제

---

dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/CheckAuthCodeService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/CheckAuthCodeServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/service/impl/CommandAuthCodeServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/spi/QueryAuthCodePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/CertifyEmailCodeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/auth/AuthCodePersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt

merge: (#575) 이메일 인증 코드 여러번 전송 시 검증 실패

---

.githooks/pre-push
build.gradle.kts

merge: (#577) Git Hooks 적용

---

dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/service/WriteFileServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/file/spi/WriteFilePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/ExportPointHistoryUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/ImportStudentUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/repository/PointHistoryJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt

feat: (#582) 엑셀 출력 api

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-infrastructure/src/test/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapterTests.kt

merge: 상벌점 엑셀 수정

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/point/PointWebAdapter.kt

merge: (#586) 외출 신청 엑셀 출력 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/OutingHistoryVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetOutingAvailableTimesUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryOutingHistoryVO.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt

merge: (#589) outingStatus 컬럼 추가

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/token/GenerateJwtAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/auth/RefreshTokenPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/auth/entity/RefreshTokenEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/auth/repository/RefreshTokenRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointOptionPersistenceAdapter.kt

merge: (#592) 토큰 중복 문제

---

dms-core/src/main/kotlin/team/aliens/dms/domain/manager/spi/vo/StudentWithTag.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/dto/StudentResponse.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/repository/vo/QueryStudentsWithTagVO.kt

feat: (#595) response에 point 정보 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingStatus.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ApplyOutingUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetOutingHistoryDetailsUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt

merge: (#598) 외출 상태 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/OutingResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/vo/CurrentOutingApplicationVO.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/vo/QueryCurrentOutingApplicationVO.kt

merge: (#603) 현재 외출 신청 id 반환

---

dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/GetPointServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/spi/QueryPointHistoryPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/spi/vo/StudentTotalVO.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/CommandTagServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/service/GetTagServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/CommandStudentTagPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryStudentTagPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/QueryTagPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/spi/StudentTagPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/StudentTagScheduler.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/repository/vo/QueryStudentTotalVO.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/StudentTagPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/TagPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/repository/StudentTagJpaRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/tag/repository/TagJpaRepository.kt

feat: (#602) 벌점 태그 자동 부여 스케줄러 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/school/dto/SchoolResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/model/AvailableFeature.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/usecase/QueryAvailableFeaturesUseCase.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/school/stub/SchoolStub.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/school/entity/AvailableFeatureJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/school/mapper/AvailableFeatureMapper.kt

merge: (#614) available feature에 outingService 추가

---

dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt

- 이름을 정확하게 입력하는게 아니라 일부만 포함 시켜도 검색이 가능
- resolved #611

merge: (#611) 외출 검색 로직 변경

---

dms-infrastructure/src/main/resources/db/migration/V3__update_out_at_to_outing_date.sql
dms-infrastructure/src/main/resources/db/migration/V4__add_outingService_in_to_tbl_available_feature.sql

merge: (#616) flyway 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt

- 
- 해당 메서드 삭제
- resolved #618

fix: (#616) 외출 신청 조건 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/bug/dto/CreateBugReportRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/model/BugAttachment.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/model/BugReport.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/model/BugType.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/model/DevelopmentArea.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/BugService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/CommandBugService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/service/CommandBugServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/spi/BugPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/spi/CommandBugPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/bug/usecase/CreateBugReportUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/bug/stub/BugStub.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-infrastructure/src/main/resources/db/migration/V5_create_tbl_bug_report&attachment.sql
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/BugPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/entity/BugAttachmentJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/entity/BugReportJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/mapper/BugReportMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/bug/repository/BugJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/bug/BugWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/bug/dto/BugType.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/bug/dto/CreateBugReportWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/bug/dto/DevelopmentArea.kt

- 버그 제보 기능 추가
- 
- resolved #609

feat: (#609) 버그 제보 기능 추가

---

dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt

- 자신이 동행자인 경우도 쿼리 결과에 포함
- resolved #625

chore: (#625) 내 외출 신청 조회 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/tag/model/WarningTag.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt

- 완료 상태일 때에만 다음 단계로 넘어가게 함
- 다음 단계로 넘어갈 때 이전 단계를 건너 뛰지 않게 함
- resolved #632

chore: (#632) 로직 수정

---

dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt

- inner join 으로 변경
(디버깅 결과 inner join 으로 변경시 컬럼이 겹치거나 이상한 상벌점이 기록되지 않는 걸 확인)
- 조건 최적화
(studentName 이 같은지의 여부는 eqGcn으로 진작에 증명 되니까 필요 없음)
- resolved #634

chore: (#634) query 수정

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt

chore: (#637) 폭 넓이 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/response/SetOutingAvailableTimeResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/exception/OutingErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/exception/OutingExceptions.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/CommandOutingTimePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingAvailableTimePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/RemoveOutingAvailableTimeUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingAvailableTimePersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt

merge: (#640) 외출 가능 시간 삭제 API

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingTimeRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTime.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/SetOutingAvailableTimeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UpdateOutingAvailableTimeUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingAvailableTimeWebRequest.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/UpdateOutingAvailableTimeWebRequest.kt

- 네이밍 수정 
start_time -> outing_time
end_time -> arrival_time
- resolved #642

merge: (#642) 외출 가능 시간 수정 API

---

dms-core/src/main/kotlin/team/aliens/dms/domain/tag/usecase/UpdateStudentTagsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/MealScheduler.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/NeisFeignClientAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/point/PointHistoryPersistenceAdapter.kt

- 쿼리 수정
- resolved #647 
- related #634

merge: (#647) 학생 태그 스케줄러 api 쿼리 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTime.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/EnableOutingAvailableTimeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/ToggleOutingAvailableTimeUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UpdateOutingAvailableTimeUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt

merge: (#649) 외출 가능 시간 활성화 여부 변경

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/MealScheduler.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/api/NeisFeignClientAdapter.kt

merge: (#652) 시간 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingTimeRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/SetOutingAvailableTimeUseCase.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingAvailableTimeWebRequest.kt

- outingTime -> startTime
- arrivalTime -> endTime
- resolved #655

merge: (#655) 변수 임시 수정

---

.github/workflows/xquare-cd-dev.yml
.github/workflows/xquare-cd-prod.yml
Dockerfile

merge: (#660) fcm 환경변수 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingCompanionPort.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingCompanionsPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/repository/OutingCompanionJpaRepository.kt

merge: (#657) 외출 신청 중복 예외처리

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/GetCurrentOutingApplicationUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt

merge: (#658) 동행자 외출 신청 내역 조회 버그

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingTimeRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/SetOutingAvailableTimeUseCase.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/OutingWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/outing/dto/request/SetOutingAvailableTimeWebRequest.kt

- startTime -> outingTime
- endTime -> arrivalTime
- 
- resolved #666

merge: (#666) 변수명 재수정

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/ExcelAdapter.kt

- formatWorkSheet를 하나 더 만들어서 컬럼 넓이를 해당 엑셀에 맞게 설정했어요
- 
- resolved #668

merge: (#668) 컬럼 넓이 수정  로직 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CheckNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CheckNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/NotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/repository/DeviceTokenJpaRepository.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/AuthWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt

- 로그인 req DTO 에 deviceToken 추가
- 로그인시 유저가 토큰을 갖고 있지 않을 경우 토큰 등록
- resolved #663

merge: (#663) 로그인에 deviceToken 등록 추가

---

dms-infrastructure/src/main/resources/application.yml

merge: (#673) flyway 환경 변수 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Topic.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/model/PointHistory.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/model/PointOption.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt

merge: (#682) 상벌점 알림 토픽 추가

---

dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Topic.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/event/EventAdapter.kt

merge: (#683) 외출 알림 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/CommandNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/CommandNotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/DeleteOldNotificationsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/NotificationScheduler.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/NotificationOfPersistenceAdapterOfUser.kt

merge: (#687) 알림 삭제 스케줄러

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Notification.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/model/Topic.kt

- 외출에 대한 알림이 공지 알림으로 설정되어 있었음
- 알림 response 값 수정 (title, content 삭제)
- resolved #691

merge: (#691) 외출 알림 버그 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/SubscribeTopicUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/UnsubscribeTopicUseCase.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/dto/request/TopicRequest.kt

merge: (#701) device_token으로 이름 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/service/GetNotificationServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryNotificationOfUserPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/QueryAndReadMyNotificationsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/NotificationOfPersistenceAdapterOfUser.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/notification/NotificationWebAdapter.kt

merge: (#697) 알림조회 페이징 처리 삭제

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/dto/TopicSubscriptionResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/usecase/QueryTopicSubscriptionUseCase.kt

merge: (#695) 알림 구독여부 기본값 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CommandOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/service/CommandPointServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/point/usecase/GrantPointUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt

- nullable 매개변수 추가
- resolved #709

merge: (#709) 상벌점 부여시 알람 발송 로직 수정

---

dms-infrastructure/src/main/resources/banner.txt

meage: (#712) banner 적용

---

dms-core/src/main/kotlin/team/aliens/dms/common/spi/EventPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notice/service/CommandNoticeServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/notification/spi/QueryDeviceTokenPort.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/event/EventAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/notification/DeviceTokenPersistenceAdapter.kt

merge: (#714) notification 분리

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/usecase/UpdateOutingAvailableTimeUseCase.kt

merge: (#719) 외출 가능 시간 수정 버그

---

dms-infrastructure/src/main/resources/banner.txt

chore: (#725) 빌드 배너 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/auth/dto/SignInRequest.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/auth/dto/request/SignInWebRequest.kt

- default 값을 없애고 nullcheck 분기를 추가해 수정
- resolved #672

merge: (#711) nullable & null체크 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/auth/usecase/SignInUseCase.kt

merge: (#729) 로그인 device token blank 체크 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/GradeCondition.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/Volunteer.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/VolunteerApplication.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerApplicationJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerApplicationMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerApplicationJpaRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/repository/VolunteerJpaRepository.kt

- 봉사, 봉사 신청 엔티티, 도메인 클래스, 매퍼 추가
- 
- resolved #731

merge: 봉사, 봉사 신청 엔티티 매핑

---

dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/VolunteerApplication.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerApplicationJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerApplicationMapper.kt

merge: (#734) 봉사 신청 approved 컬럼 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/volunteer/model/Volunteer.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/mapper/VolunteerMapper.kt

merge: (#738) 봉사 schoolId 컬럼 추가

---

dms-infrastructure/src/main/resources/db/migration/V4__create_tbl_volunteer_and_attachment.sql
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/volunteer/entity/VolunteerApplicationJpaEntity.kt

- 휴먼에러 fix ( biinary(16) -> binary(16) )
- 
- resolved #740

merge: 740 flyway 스크립트 작성

---

dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt

merge: (#754) 학생 전체 조회 오류 수정

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt

merge: (#761) 캐시 삭제

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/thirdparty/parser/port/ExcelPort.kt

merge: (#765) 엑셀 너비 증가

---

build.gradle.kts
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt

- default(전체 메모리의 1/8) 에서 4G~1G 로 변경 (X)
- resolved #780

merge: (#780) CD 빌드 오류 해결

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/GetOutingServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/spi/QueryOutingApplicationPort.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/outing/OutingApplicationPersistenceAdapter.kt

- 쿼리에 조건 추가
- service 단계에서 매개변수로 LocalDate.now() 가 들어가도록 설정
- resolved #791

merge: (#791) 내 외출 신청 오늘만 조회되도록 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTime.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/outing/service/CheckOutingServiceImpl.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/outing/model/OutingAvailableTimeTest.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/volunteer/VolunteerTest.kt
dms-core/src/test/kotlin/team/aliens/dms/domain/volunteer/stub/VolunteerStub.kt

테스트 코드 작성
봉사 승인이 되어있지 않을 경우
외출 시간 겹칠 경우
- resolved #793

merge: (#793) 외출, 봉사 신청 테스트 코드 작성

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/model/Vote.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/model/VoteType.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/model/VotingOption.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/model/VotingTopic.kt
dms-infrastructure/src/main/resources/db/migration/V10_create_tbl_vote_and_voting_option.sql
dms-infrastructure/src/main/resources/db/migration/V11_create_tbl_vote_and_voting_option.sql
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/entity/VoteJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/entity/VotingOptionJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/entity/VotingTopicJpaEntity.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/mapper/VoteMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/mapper/VotingOptionMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/mapper/VotingTopicMapper.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VoteJpaRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VotingOptionJpaRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VotingTopicJpaRepository.kt

- votingTopicJpaEntity 및 도메인 추가
- votingOptionJpaEntity 및 도메인 추가
- voteJpaEntity 및 도메인 추가
- 투표를 위한 새로운 도메인 추가
- resolved #806

merge:(#806) 투표 관련 엔티티 생성

---

.github/CODEOWNERS
.github/workflows/xquare-cd-dev.yml

배포 잘 되는지 테스트합니다
코드 오너에 1학년들 추가합니다
- resolved #818

chore: (#818) 쓸모없는 환경변수 제거

---

dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotingOptionPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotingTopicPersistenceAdapter.kt

- 컴포넌트 누락 수정
- 컴포넌트 누락 수정
- resolved #836

merge: (#836) 컴포넌트 등록

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VoteResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VotesResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVoteUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVoteUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVotingOptionUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryVotesUseCase.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/dto/request/CreateVotingOptionWebRequest.kt

- 투표 결과를 출력할 수 있는 api를 생성 했습니다
- 투표 결과 조회 api 생성
- resolved #813

merge: (#813) 투표 결과 조회 api 생성

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/reponse/VoteResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/GetVoteServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandExcludedStudentPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/ExcludedStudentPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/QueryExcludedStudentPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryAllExcludedStudentUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryAllExcludedStuentUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/ExcludedStudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt

* 모범학생 후보에서 제외된 학생 전체조회 api를 추가했습니다.
* 모범학생 후보 제외 학생 전체조회 api 
- resolved #826

merge: (#826) 모범학생 후보에서 제외된 학생 전체 조회 api 추가

---

dms-infrastructure/src/main/resources/db/migration/V13__create_tbl_excluded_student.sql

* 마이그레이션 v 13 실행안됨 오류 수정
* migration v13
- resolved #851

merge: (#851) 마이그레이션 v13 실행안됨 오류 수정

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt

- securityConfig 수정
- 프로젝트 패키지 변경으로 인해 SecurityConfig를 추가하지 못함 -> 추가
- resolved #853

merge: (#853) Security Config 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/CreateVotingTopicResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VoteResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVotingTopicUseCase.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt

- CreateVotingTopic에서 Id를 리턴 하도록 변경
- CreateVotingTopic에서 Id를 리턴 하도록 변경
- resolved #857

merge: (#857) VotingTopic 생성 시 id를 리턴하도록 변경

---

dms-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt

- VoteWebAdapter에서 올바른 UseCase를 사용하도록 변경
- VoteWebAdapter에서 올바른 UseCase를 사용하도록 변경
- resolved #861

merge: (#861) VoteWebAdapter 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/student/spi/QueryStudentPort.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt

* SecurityConfig 수정 및 학교 ID 조회 방식 변경하였습니다
* SecurityConfig 수정 및 학교 ID 조회 방식 변경하였습니다
- resolved #864

merge: (#864) SecurityConfig 수정 및 학교 ID 조회 방식 변경

---

dms-infrastructure/src/main/kotlin/team/aliens/dms/global/security/SecurityConfig.kt

* Security Config 추가하였습니다
* Security Config에 admin 권한 설정을 추가하였습니다
- resolved #871

merge: (#871) Security Config 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandExcludedStudentPort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/ClearExcludedStudentsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteAllExcludedStudentsUseCase.kt
dms-infrastructure/src/main/kotlin/team/aliens/dms/scheduler/ExcludedStudentScheduler.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/ExcludedStudentPersistenceAdapter.kt

* ExcludedStudent 초기화 로직을 추가하였습니다
* ExcludedStudent 초기화 로직을 추가하였습니다
- resolved #869

merge: (#869) ExcludedStudent 초기화 로직 추가

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateExcludedStudentUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/mapper/ExcludedStudentMapper.kt

* 모범학생 제외학생 추가 수정
* CreateExcludedStudentUseCase
- resolved #874

merge: (#874) 모범학생 제외학생 추가 수정

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVotingTopicUseCase.kt

- 찬반 투표 시 투표 항목 자동 생성
- 찬반 투표 시 투표 항목 자동 생성
- resolved #863

merge: (#863) 찬반 투표 생성시 투표 항목 자동 생성

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VoteResponse.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryAllExcludedStudentUseCase.kt

* dto 필드 이름 변경
* VoteResponse 필드 이름 변경
- resolved #876

merge: (#876) studentId -> id 로 변경

---

dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteService.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/service/CommandVoteServiceImpl.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandVotePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVotingOptionUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVotingTopicUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotePersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VoteJpaRepository.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VotingOptionJpaRepository.kt

- 고아 객체 삭제 오류 수정
- resolved #860

merge: (#860) 고아 객체 삭제 문제 수정

---

dms-core/src/main/kotlin/team/aliens/dms/common/error/ErrorStatus.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/auth/exception/error/AuthErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/school/exception/error/SchoolErrorCode.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/spi/CommandVotePort.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateExcludedStudentUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/CreateVotingTopicUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteAllExcludedStudentsUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/DeleteVotingOptionUseCase.kt
dms-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryVotesUseCase.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/VotePersistenceAdapter.kt
dms-persistence/src/main/kotlin/team/aliens/dms/persistence/vote/repository/VoteJpaRepository.kt

password-mismatch status 422 로 변경
* ErrorStatus enum 타입 UNPROCESSABLE_ENTITY 추가
* PASSWORD_MISMATCH enum값의 stastus 값을 기존 401 에서 를 422 로 변경
- resolved #889

merge: (#889) password-mismatch status 422 로 변경

---

.dockerignore
.github/workflows/xquare-cd-dev.yml
.github/workflows/xquare-cd-prod.yml
dms-main/Dockerfile

* docker file build 포함 멀티 스테이지 구성으로 변경.
* 기존 cd 용 gitAction 파일 주석처리
* dockerignore 추가
* docker file
* dockerignore
* .github/workflows/xquare-cd-dev.yml
* .github/workflows/xquare-cd-prod.yml
설계문서들
https://tough-aster-38a.notion.site/25cd155f8ab7803eb533d67e4b17e447?pvs=74
https://tough-aster-38a.notion.site/Dockerignore-25dd155f8ab780649adece3e7bf57a93?source=copy_link
도커 파일에 대한 자세한 내용
https://github.com/uyjeamin/Today-I-Learn/blob/main/%EC%A0%84%EA%B3%B5/DevOps/docker/dockerfile/dms%20%EB%8F%84%EC%BB%A4%20%ED%8C%8C%EC%9D%BC.md
- resolved #901

merge: (#901) 배포 플로우 변경

---

dms-main/main-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentService.kt
dms-main/main-core/src/main/kotlin/team/aliens/dms/domain/student/service/GetStudentServiceImpl.kt
dms-main/main-core/src/main/kotlin/team/aliens/dms/domain/student/spi/vo/ModelStudentVO.kt
dms-main/main-core/src/main/kotlin/team/aliens/dms/domain/student/usecase/GetModelStudentsUseCase.kt
dms-main/main-core/src/main/kotlin/team/aliens/dms/domain/vote/dto/response/VoteResponse.kt
dms-main/main-core/src/main/kotlin/team/aliens/dms/domain/vote/usecase/QueryAllExcludedStudentUseCase.kt
dms-main/main-persistence/src/main/kotlin/team/aliens/dms/persistence/student/StudentPersistenceAdapter.kt
dms-main/main-presentation/src/main/kotlin/team/aliens/dms/domain/student/StudentWebAdapter.kt
dms-main/main-presentation/src/main/kotlin/team/aliens/dms/domain/vote/VoteWebAdapter.kt

* 팀 컨벤션에 맞게 기존에 있던 모범학생 조회 api를 리팩토링 했습니다
- resolved #908

merge: (#908) 팀 컨벤션에 맞게 코드 리팩토링
